- hosts: all
  become: true
  tasks:
    - name: Delete existing minikube cluster if exists
      command: minikube delete
      ignore_errors: yes
      
    - name: Start minikube
      command: minikube start --driver=docker
      register: minikube_start
      
    - name: Wait for minikube to be ready
      shell: minikube status
      register: status_output
      until: status_output.rc == 0
      retries: 6
      delay: 10
      
    - name: Get minikube status
      command: minikube status
      register: minikube_status
      
    - name: Create kube config directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'
        
    - name: Copy kube config
      shell: |
        minikube kubectl -- config view --flatten > {{ ansible_env.HOME }}/.kube/config
        chmod 600 {{ ansible_env.HOME }}/.kube/config
        
    - name: Wait for kubernetes API to be available
      shell: kubectl get nodes
      register: api_status
      until: api_status.rc == 0
      retries: 6
      delay: 10
      
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yaml
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      
    - name: create new service
      command: kubectl apply -f /home/ubuntu/Service.yaml
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"