- hosts: webapp-server
  become: true
  tasks:

    - name: create new deployment
      command: kubectl apply --validate=false -f /home/ubuntu/Deployment.yaml

      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        
    - name: create new service
      command: kubectl apply --validate=false -f /home/ubuntu/Service.yaml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config