kind: Service                             
apiVersion: v1
metadata:
  name: webapp-deployment
  labels:
    app: webapp-deployment
spec:
  type: NodePort                   
  ports:
    # - port: 8080                              
      targetPort: 80
      nodePort: 32145
  selector:
    app: webapp-deployment                    
